# Generated by Django 2.1.7 on 2019-03-05 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20190305_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='creation_date',
            field=models.DateTimeField(verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='post',
            name='modification_date',
            field=models.DateTimeField(blank=True, verbose_name='date modified'),
        ),
    ]
