# Generated by Django 2.1.7 on 2019-03-05 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20190305_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(blank=True, through='news.CategoryToPost', to='news.Category'),
        ),
    ]
