# Generated by Django 2.1.7 on 2019-03-17 14:54

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0006_auto_20190313_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('article_content', models.CharField(max_length=200, null=True)),
                ('slug', models.SlugField(max_length=255, unique_for_date='publication_date', verbose_name='slug')),
                ('text', models.TextField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('publication_date', models.DateTimeField(db_index=True, default=datetime.datetime(2019, 3, 17, 15, 54, 4, 913584))),
                ('modification_date', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, 'Offline'), (1, 'Online')], db_index=True, default=0, verbose_name='status')),
                ('read_status', models.BooleanField(default=False)),
                ('bookmark_status', models.BooleanField(default=False)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='categorytopost',
            name='post',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.AddField(
            model_name='article',
            name='categories',
            field=models.ManyToManyField(blank=True, through='news.CategoryToPost', to='news.Category'),
        ),
        migrations.AddField(
            model_name='categorytopost',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.Article'),
        ),
    ]
