# Generated by Django 2.1.7 on 2019-03-31 10:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_auto_20190324_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publication_date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2019, 3, 31, 12, 48, 55, 782157)),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(choices=[('1', 'Diagnostic'), ('2', 'PADD'), ('3', 'Concertation')], max_length=20),
        ),
    ]
