# Generated by Django 2.1.3 on 2018-12-13 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistiques',
            name='txevoansoldmig_1015',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='txevoansoldmig_6875',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='txevoansoldmig_7582',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='txevoansoldmig_8290',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='txevoansoldmig_9099',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='txevoansoldmig_9910',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='txevoansoldnat_1015',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='txevoansoldnat_6875',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='txevoansoldnat_7582',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='txevoansoldnat_8290',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='txevoansoldnat_9099',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='txevoansoldnat_9910',
            field=models.FloatField(null=True),
        ),
    ]
