# Generated by Django 2.1.3 on 2018-12-18 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20181218_1049'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Statistiques',
            new_name='DataBase',
        ),
    ]
