# Generated by Django 2.1.3 on 2018-12-05 12:38

from django.db import migrations, models
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dataviz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MushroomSpot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', djgeojson.fields.PointField()),
            ],
        ),
    ]
