# Generated by Django 2.1.3 on 2018-12-05 13:03

from django.db import migrations, models
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dataviz', '0002_mushroomspot'),
    ]

    operations = [
        migrations.AddField(
            model_name='mushroomspot',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='mushroomspot',
            name='picture',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='mushroomspot',
            name='title',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='mushroomspot',
            name='geom',
            field=djgeojson.fields.PolygonField(),
        ),
    ]
