# Generated by Django 2.1.3 on 2018-12-18 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataviz', '0002_auto_20181213_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistiques',
            name='au2010',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='bv2012',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='c10_mencoupaenf',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='c10_mencoupsenf',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='c10_menfam',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='c10_menfammono',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='c10_menpseul',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='c10_mensfam',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='c10_ne24f0',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='c10_ne24f1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='c10_ne24f2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='c10_ne24f3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='c10_ne24f4p',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='c10_pop15p',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='c10_pop15p_cs1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='c10_pop15p_cs2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='c10_pop15p_cs3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='c10_pop15p_cs4',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='c10_pop15p_cs5',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='c10_pop15p_cs6',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='c10_pop15p_cs7',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='c10_pop15p_cs8',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='c10_txmencoupaenf',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='c10_txmencoupsenf',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='c10_txmenfam',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='c10_txmenfammono',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='c10_txmenpseul',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='c10_txmensfam',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='c10_txne24f0',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='c10_txne24f1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='c10_txne24f2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='c10_txne24f3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='c10_txne24f4p',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='c10_txpop15p_cs1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='c10_txpop15p_cs2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='c10_txpop15p_cs3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='c10_txpop15p_cs4',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='c10_txpop15p_cs5',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='c10_txpop15p_cs6',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='c10_txpop15p_cs7',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='c10_txpop15p_cs8',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='c15_mencoupaenf',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='c15_mencoupsenf',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='c15_menfam',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='c15_menfammono',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='c15_menpseul',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='c15_mensfam',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='c15_ne24f0',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='c15_ne24f1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='c15_ne24f2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='c15_ne24f3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='c15_ne24f4p',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='c15_pop15p',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='c15_pop15p_cs1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='c15_pop15p_cs2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='c15_pop15p_cs3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='c15_pop15p_cs4',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='c15_pop15p_cs5',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='c15_pop15p_cs6',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='c15_pop15p_cs7',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='c15_pop15p_cs8',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='c15_txmencoupaenf',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='c15_txmencoupsenf',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='c15_txmenfam',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='c15_txmenfammono',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='c15_txmenpseul',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='c15_txmensfam',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='c15_txne24f0',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='c15_txne24f1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='c15_txne24f2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='c15_txne24f3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='c15_txne24f4p',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='c15_txpop15p_cs1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='c15_txpop15p_cs2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='c15_txpop15p_cs3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='c15_txpop15p_cs4',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='c15_txpop15p_cs5',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='c15_txpop15p_cs6',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='c15_txpop15p_cs7',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='c15_txpop15p_cs8',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='coefmulti_1015',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='coefmulti_6875',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='coefmulti_7582',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='coefmulti_8290',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='coefmulti_9099',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='coefmulti_9910',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='d68_log',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='d68_logvac',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='d68_nper_rp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='d68_rp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='d68_rsecocc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='d75_log',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='d75_logvac',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='d75_nper_rp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='d75_rp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='d75_rsecocc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='d82_log',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='d82_logvac',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='d82_nper_rp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='d82_rp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='d82_rsecocc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='d90_log',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='d90_logvac',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='d90_nper_rp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='d90_rp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='d90_rsecocc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='d99_log',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='d99_logvac',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='d99_pmen',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='d99_rp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='d99_rsecocc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='dece1015',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='dece6875',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='dece7582',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='dece8290',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='dece9099',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='dece9910',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='libau2010',
            field=models.CharField(blank=True, max_length=46, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='libbv2012',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='nais1015',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='nais6875',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='nais7582',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='nais8290',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='nais9099',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='nais9910',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p1015_txevoanpop0014',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p1015_txevoanpop1529',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p1015_txevoanpop3044',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p1015_txevoanpop4559',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p1015_txevoanpop6074',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p1015_txevoanpop75p',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p10_act1564',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p10_actocc1564',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p10_appart',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p10_chom1564',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p10_emplt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p10_f0019',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p10_h0019',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p10_indconemp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p10_indjeun',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p10_log',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p10_logvac',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p10_maison',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p10_men_anem0002',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p10_men_anem0204',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p10_men_anem0509',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p10_men_anem1019',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p10_men_anem10p',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p10_men_anem2029',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p10_men_anem30p',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p10_pmen',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p10_pop0014',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p10_pop0019',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p10_pop1529',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p10_pop1564',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p10_pop3044',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p10_pop4559',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p10_pop6074',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p10_pop75p',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p10_rp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p10_rp_1p',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p10_rp_2p',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p10_rp_3p',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p10_rp_4p',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p10_rp_5pp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p10_rp_grat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p10_rp_loc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p10_rp_lochlmv',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p10_rp_locpriv',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p10_rp_prop',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p10_rsecocc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p10_txact',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p10_txappart',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p10_txchom',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p10_txmaison',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p10_txmen_anem0002',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p10_txmen_anem0204',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p10_txmen_anem0509',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p10_txmen_anem1019',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p10_txmen_anem10p',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p10_txmen_anem2029',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p10_txmen_anem30p',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p10_txpop0014',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p10_txpop1529',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p10_txpop3044',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p10_txpop4559',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p10_txpop6074',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p10_txpop75p',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p10_txrp_1p',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p10_txrp_2p',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p10_txrp_3p',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p10_txrp_4p',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p10_txrp_5pp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p10_txrp_grat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p10_txrp_loc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p10_txrp_lochlmv',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p10_txrp_locpriv',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p10_txrp_prop',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_1519dp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_1519ind',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_2024app',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_2024dp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_2024grat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_2024ind',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_2024lochlm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_2024locpriv',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_2024mai',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_2024prop',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_2529dp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_2529ind',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_2539app',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_2539grat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_2539lochlm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_2539locpriv',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_2539mai',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_2539prop',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_3034dp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_3034ind',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_6579app',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_6579grat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_6579lochlm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_6579locpriv',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_6579mai',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_6579prop',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_80app',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_80grat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_80lochlm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_80locpriv',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_80mai',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_80prop',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_act1564',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_actocc1564',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_appart',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_chom1564',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_emplt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_f0019',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_h0019',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_indconemp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_indjeun',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_log',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_logvac',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_maison',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_men_anem0002',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_men_anem0204',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_men_anem0509',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_men_anem1019',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_men_anem10p',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_men_anem2029',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_men_anem30p',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_pmen',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_pop0014',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_pop0019',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_pop01p',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_pop01p_iran1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_pop01p_iran2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_pop01p_iran3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_pop01p_iran4',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_pop01p_iran5',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_pop01p_iran6',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_pop01p_iran7',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_pop1529',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_pop1564',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_pop3044',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_pop4559',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_pop6074',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_pop7589',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_pop75p',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_pop90p',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_rp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_rp_1p',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_rp_2p',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_rp_3p',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_rp_4p',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_rp_5pp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_rp_ach05',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_rp_ach12',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_rp_ach19',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_rp_ach45',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_rp_ach70',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_rp_ach90',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_rp_achtot',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_rp_cindelec',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_rp_grat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_rp_loc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_rp_lochlmv',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_rp_locpriv',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_rp_prop',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_rp_sdb',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_rsecocc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_taillemoy_rpappart',
            field=models.FloatField(blank=True, db_column='P15_taillemoy_rpappart', null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_taillemoy_rpmaison',
            field=models.FloatField(blank=True, db_column='P15_taillemoy_rpmaison', null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_tx1519dp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_tx1519ind',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_tx2024app',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_tx2024dp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_tx2024grat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_tx2024ind',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_tx2024lochlm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_tx2024locpriv',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_tx2024mai',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_tx2024prop',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_tx2529dp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_tx2529ind',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_tx2539app',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_tx2539grat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_tx2539lochlm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_tx2539locpriv',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_tx2539mai',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_tx2539prop',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_tx3034dp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_tx3034ind',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_tx6579app',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_tx6579grat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_tx6579lochlm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_tx6579locpriv',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_tx6579mai',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_tx6579prop',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_tx80app',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_tx80grat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_tx80lochlm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_tx80locpriv',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_tx80mai',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_tx80prop',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_txact',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_txappart',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_txchom',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_txmaison',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_txmen_anem0002',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_txmen_anem0204',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_txmen_anem0509',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_txmen_anem1019',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_txmen_anem10p',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_txmen_anem2029',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_txmen_anem30p',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_txpop0014',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_txpop01p',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_txpop01p_iran1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_txpop01p_iran2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_txpop01p_iran3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_txpop01p_iran4',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_txpop01p_iran5',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_txpop01p_iran6',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_txpop01p_iran7',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_txpop1529',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_txpop3044',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_txpop4559',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_txpop6074',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_txpop7589',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_txpop75p',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_txpop90p',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_txrp_1p',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_txrp_2p',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_txrp_3p',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_txrp_4p',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_txrp_5pp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_txrp_ach05',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_txrp_ach12',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_txrp_ach19',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_txrp_ach45',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_txrp_ach70',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_txrp_ach90',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_txrp_chauf',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_txrp_grat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_txrp_loc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_txrp_lochlmv',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_txrp_locpriv',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_txrp_prop',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='p15_txrp_sdb',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='popb100_1068',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='popb100_1568',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='popb100_68',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='popb100_7568',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='popb100_8268',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='popb100_9068',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='popb100_9968',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='soldmig_1015',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='soldmig_6875',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='soldmig_7582',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='soldmig_8290',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='soldmig_9099',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='soldmig_9910',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='soldnat_1015',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='soldnat_6875',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='soldnat_7582',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='soldnat_8290',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='soldnat_9099',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='soldnat_9910',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='tailmmen_10',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='tailmmen_15',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='tailmmen_68',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='tailmmen_75',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='tailmmen_82',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='tailmmen_90',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='tailmmen_99',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='txacc_1015',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='txacc_6875',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='txacc_7582',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='txacc_8290',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='txacc_9099',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='txacc_9910',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='txevoan_logvacan_1015',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='txevoapp_1015',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='txevograt_1015',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='txevohlmv_1015',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='txevolocpriv_1015',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='txevolrsec_1015',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='txevoma_1015',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='txevopopan_1015',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='txevopopan_6875',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='txevopopan_7582',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='txevopopan_8290',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='txevopopan_9099',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='txevopopan_9910',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='txevoprop_1015',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='txevot1_1015',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='txevot2_1015',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='txevot3_1015',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='txevot4_1015',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='txevot5_1015',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='txlogvac_10',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='txlogvac_15',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='txlogvac_68',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='txlogvac_75',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='txlogvac_82',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='txlogvac_90',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='txlogvac_99',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='txrp_10',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='txrp_15',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='txrp_68',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='txrp_75',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='txrp_82',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='txrp_90',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='txrp_99',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='txrsec_10',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='txrsec_15',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='txrsec_68',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='txrsec_75',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='txrsec_82',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='txrsec_90',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistiques',
            name='txrsec_99',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='statistiques',
            name='codgeo',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='statistiques',
            name='d68_pop',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='statistiques',
            name='d75_pop',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='statistiques',
            name='d82_pop',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='statistiques',
            name='d90_pop',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='statistiques',
            name='d99_pop',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='statistiques',
            name='dep',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='statistiques',
            name='epci',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='statistiques',
            name='libdep',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='statistiques',
            name='libepci',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='statistiques',
            name='libgeo',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='statistiques',
            name='libreg',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='statistiques',
            name='p10_pop',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='statistiques',
            name='p15_pop',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='statistiques',
            name='reg',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='statistiques',
            name='txevoansoldmig_1015',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='statistiques',
            name='txevoansoldmig_6875',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='statistiques',
            name='txevoansoldmig_7582',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='statistiques',
            name='txevoansoldmig_8290',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='statistiques',
            name='txevoansoldmig_9099',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='statistiques',
            name='txevoansoldmig_9910',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='statistiques',
            name='txevoansoldnat_1015',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='statistiques',
            name='txevoansoldnat_6875',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='statistiques',
            name='txevoansoldnat_7582',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='statistiques',
            name='txevoansoldnat_8290',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='statistiques',
            name='txevoansoldnat_9099',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='statistiques',
            name='txevoansoldnat_9910',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='statistiques',
            name='varpop_1015',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='statistiques',
            name='varpop_6875',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='statistiques',
            name='varpop_7582',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='statistiques',
            name='varpop_8290',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='statistiques',
            name='varpop_9099',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='statistiques',
            name='varpop_9910',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
